=== TsunagariEngine/Tsunagari/src/dtd/sprite.dtd
<!ELEMENT tsunagari (sprite)>
<!ATTLIST tsunagari version (1) #REQUIRED>

<!ELEMENT sprite (sheet, phases)>
<!ATTLIST sprite version (1) #REQUIRED>

<!ELEMENT sheet (#PCDATA)>
<!ATTLIST sheet tilesizex CDATA #REQUIRED
                tilesizey CDATA #REQUIRED>

<!ELEMENT phases (phase+)>

<!ELEMENT phase (member*)>
<!ATTLIST phase name  CDATA #REQUIRED
                pos   CDATA #IMPLIED
                speed CDATA #IMPLIED>

<!ELEMENT member EMPTY>
<!ATTLIST member pos CDATA #REQUIRED>

=== TsunagariEngine/Tsunagari/src/babysfirst/sprite.example.xml
<!DOCTYPE tsunagari SYSTEM "dtd/sprite.dtd">

<tsunagari version="1">
	<sprite version="1">
		<sheet file="tileset.sheet" tilesizex="64" tilesizey="64" />
		<phases>
			<phase name="wall" pos="0" />
			<phase name="red" pos="1" />
			<phase name="yellow" pos="2" />
			<phase name="blue" pos="3" />
			<phase name="purple" pos="4" />
			<phase name="green" pos="5" />
			<phase name="orange" pos="6" />
			<phase name="lightblue" pos="7" />
			<phase name="dirt" pos="8" />
			<phase name="water" pos="9" />
			<phase name="marble" pos="10" />
			<phase name="checker" pos="11" />
			<phase name="teleblue" pos="12" />
			<phase name="telered" pos="13" />
			<phase name="testanimation" speed="4">
				<member pos="14" />
				<member pos="15" />
			</phase>
		</phases>
	</sprite>
</tsunagari>
